### PR TITLE
Finished flag and redflag

### PR DESCRIPTION
**Pull request by SahilGhosalkar**
WE BRING THE BOOM!

### CODE REVIEW

**Comment by SahilGhosalkar** [comment]
hurry up zoya

**Comment by zoyaio** [comment]
Need getter/setters for magnitude.  A constructor with the magnitude maybe?

**Comment by SahilGhosalkar** [comment]
check again lil bro

**Comment by zoyaio** [comment]
okayyy it looks good

**Review by zoyaio — APPROVED** [review]
YAY this is fire

**Pull request merged**
